### ISSUE TITLE
Is this error due to landscaping tools?

### ISSUE THREAD

**Issue by Haneybd87** [AlphaGaming7780/ExtraLandscapingTools-BepInEx#5]
This happened when I opened the devmode Home menu. Here's the bepinex log.

[Error  : Unity Log] [UI] [ERROR]  JS Error: :71: TypeError: Cannot read properties of undefined (reading 'insertBefore')
[Error  : Unity Log] [UI] [ERROR]  JS Error (Line): ExtraLandscapingTools_toolOption.insertBefore(ExtraLandscapingTools_brushOption_item, ExtraLandscapingTools_toolOption_first)
[Error  : Unity Log] [UI] [ERROR]  JS Error (Stack): TypeError: Cannot read properties of undefined (reading 'insertBefore')
    at <anonymous>:71:34

**Comment by AlphaGaming7780** [comment]
Yeah, this error comes from ELT, can you describe a bit better how you get this ?
Do you have the landscaping tool open when  you open the devmode ?
When you open the devmod what item was selected, a porps ? A surface ? One of the landscaping tools ?

This kind of error is not critical, the game isn't going to crash and the next time you open the landscaping menu everything should be fine.

**Comment by Haneybd87** [comment]
I can't remember if I had the landscaping menu open when I opened the devmode menu, but I do know it at least opened when I opened the devmode menu. I can't remember which tab it was on but I think the brush sliders in the devmode menu were there so maybe terrain or tree brush. I can't remember what was selected in the devmode menu. 

Is it possible that this is what corrupted my last city? I had about 50 hours worth of saves that were corrupted, but I didn't realize it because it only causes the city to crash when the simulation is in june/july 2025. My first corrupt save was not long after I started using this mod, anarchy, and tree controller and I have had errors like this popup in that save, I just don't know what mod they were pointing at. I've also gotten some errors from tree controller that I reported to Yenyang so it's possible it could be from that too or something else entirely. In any case a fresh, modless install (with cleaned folders) did not fix the save corruption.

**Comment by AlphaGaming7780** [comment]
Nop, That can't corrupt a save file, it's UI code and have nothing to do with the game itself. But yeah, it's highly recommended to use auto save when playing with mod, especially now since the modding support is not out yet.

For the bug you mentioned, I can't fix that. It's an issue with the dev tool and the UI, and IDK why it's causing that, but since it's not a critical bug (id don't crash the game, or corrupt save file) I'm not going to spend too much time on that.

I'm sorry to hear your save file is corrupted, but I can do nothing about that, maybe try to play the game with the consol open and see if the game gives you an error message when you load your save file, you will maybe be able to see what happen there and fixe that.
